Allow add-on detection without layout shifts
mozilla/fx-private-relay-add-on pull request #226
Opened 2021-12-06 09:46 UTC by Vinnl

Instead of having the website wait 500ms for the add-on to inject
data into it indicating that it is installed, this change will
allow it to simply add an `is-hidden-with-addon` class, and then
the add-on will inject CSS even before the JS is executed that will
ensure that that element is not visible (or `is-visible-with-addon`
for the inverse behaviour). This means we should no longer have
the page jump around when the "Install the add-on" banner is
displayed.

2022-01-04 22:45 UTC, maxxcrawford requested changes
What's the best way to test this?

2022-01-05 14:05 UTC, Vinnl commented
@maxxcrawford You can test it by also checking out https://github.com/mozilla/fx-private-relay/pull/1402, then making sure that the banner to install the add-on is not visible with the add-on installed, but _is_ visible if it's not (and you're in Firefox).

2022-01-05 15:46 UTC, maxxcrawford requested changes
Thanks for the test steps — on Firefox without it loaded, everything works as expected.

I did notice this issue in Chrome. The current UX is that we recommend the user to try Firefox if they're visiting from a browser that doesn't support our add-on (read: Firefox only right now).

Can you make sure it's hidden entirely if not in Firefox? 

<img width="1192" alt="image" src="https://user-images.githubusercontent.com/2692333/148246431-9e0ddec7-cc48-43a7-a40a-8ffb02a522c7.png">

2022-01-05 17:33 UTC, Vinnl commented
@maxxcrawford Ooh, good catch, didn't think of that. I fixed that in https://github.com/mozilla/fx-private-relay-add-on/pull/226. Unfortunately that does mean there's still a layout shift when the banner _is_ present, but at least it'll be gone when it's not. (And it'll be entirely gone if we only have client-side rendering, since then the whole page will be rendered at the same time.)

2022-01-25 14:03 UTC, Vinnl commented
This was included in #249.

2022-01-25 14:03 UTC, closed without merging