Fix #10 - Remove z-index to stop textbox from drawing overtop other c…
mozilla/fx-private-relay-add-on pull request #99
Opened 2021-07-09 18:54 UTC by codemist

…ontent and show the email placeholder

@maxxcrawford  (Is there a limit to how long a commit message can be?)

2021-07-09 19:14 UTC, groovecoder commented
No limit on commit messages. Lots of tools truncate commit messages around 70 characters, so it's best if you can fit a summary on a single line of <70 characters, leave a blank line, and then put more details in the commit message after that. E.g.,

```
fix #10 - Remove z-index to stop textbox drawing over other content

By removing the z-index value from our element, we stop our empty 
textbox from being rendered on top of the underlying email input 
element's placeholder text.
```

2021-07-09 19:15 UTC, groovecoder commented
@lesleyjanenorton - do you remember how we settled on the super-high z-index value for our element? Were there other bugs caused by having no z-index value?

2021-07-09 19:24 UTC, codemist commented
Removing the z-index property from the textbox wrapper seem to have fixed the drawing over issue as well as restored the placeholder value in the text fields (an issue related to #18 and #13 ) 

**Tested on:** 
reddit.com
academy.newscientist.com/users/sign_in (one of the examples in the comments)
https://www.theverge.com/2020/3/24/21192048/firefox-better-web-scroll-subscription-ad-tracker-blocker-publisher-payment
dropbox.com

**Result:**
The overlay issue However, now the placeholder just stays there on some sites (like Reddit).
<img width="742" alt="image" src="https://user-images.githubusercontent.com/13066134/125125106-005da300-e0ae-11eb-84d1-452e706b1a3b.png">

For Dropbox however, this doesn't seem to be an issue.

2021-08-23 19:39 UTC, maxxcrawford commented on src/css/relay.css
> -  z-index: 99999999999999999;
Is it good to have some `z-index` here? (as is a `1` or a `0`)?

2022-01-19 15:21 UTC, maxxcrawford requested changes
I wanted to circle back on this open PR — could you test against some of the sites listed in [the referenced issue](https://github.com/mozilla/fx-private-relay-add-on/issues/10)? 

Additionally, see my previous comment about having some (much smaller) `z-index` value still in place: https://github.com/mozilla/fx-private-relay-add-on/pull/99#pullrequestreview-736498399

2022-09-22 13:35 UTC, closed without merging